name: Maven Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17.0
        uses: actions/setup-java@v2
        with:
          java-version: 17.0

      - name: Build with Maven
        run: mvn clean package
