name: Maven Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: kinitap/demo-hello-world
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 20.0
        uses: actions/setup-java@v2
        with:
          java-version: 20.0
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker Image
        run: |
            # Build the Docker image inside a container
            docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Show Docker Images
        run: docker images

      - name: Run Docker Container
        run: docker run -d --name demo-hello-world-v2 -p 8081:8081 kinitap/demo-hello-world:${{ github.sha }}

      - name: Show Docker Containers
        run: docker ps

      - name: Stop Docker Container
        run: docker stop demo-hello-world-v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push kinitap/demo-hello-world:${{ github.sha }}

