name: Maven Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 20.0
        uses: actions/setup-java@v2
        with:
          java-version: 20.0
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          IMAGE_NAME: kinitap/demo-hello-world  # Replace with your Docker Hub username and image name
          IMAGE_TAG: ${{ github.sha }}  # Replace with the desired image tag
          run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64 -t $IMAGE_NAME:$IMAGE_TAG --push .

      - name: Show Docker Images
        run: docker images

