name: Maven Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 20.0
        uses: actions/setup-java@v2
        with:
          java-version: 20.0
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: kinitap/demo-hello-world:${{ github.sha }}

      - name: Clear Docker Cache
        run: docker builder prune --force

      - name: Show Docker Images
        run: docker images

